### Signup with username and password.
POST http://0.0.0.0:8072/user/signup
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password"
}

### Login with username and password and save token.
POST http://0.0.0.0:8072/user/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Edit email address of a user.
PATCH http://0.0.0.0:8072/user/email
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{auth_token}}

newEmail=user2@example.com
