### Authorization by token, part 1. Retrieve and save token.
POST http://admin:secret@0.0.0.0:8072/login
Content-Type: application/json

> {% client.global.set("auth_token", response.body.token); %}

### Authorization by token, part 2. Use token to authorize.
GET http://0.0.0.0:8072/resource
Authorization: Bearer {{auth_token}}
