### Signup with username and password.
POST http://0.0.0.0:8072/user/signup
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password"
}

> {%
    client.test("Response status is 200", function() {
        client.assert(response.status === 200, "Expected response status to be 200, but received " + response.status);
    });

    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", `Expected 'application/json' but received '${type}'`);
    });
%}

### Login with username and password and save token.
POST http://0.0.0.0:8072/user/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password"
}

> {%
    client.test("Response status is 200", function() {
        client.assert(response.status === 200, "Expected response status to be 200, but received " + response.status);
    });
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Request video
GET http://0.0.0.0:8072/piped/streams/Kt8RupLIkBQ

> {%
    client.test("Response status is 200", function() {
        client.assert(response.status === 200, "Expected response status to be 200, but received " + response.status);
    });
%}

### Like video
PUT http://0.0.0.0:8072/like/Kt8RupLIkBQ
Authorization: Bearer {{access_token}}

> {%
    client.test("Response status is 200", function() {
        client.assert(response.status === 200, "Expected response status to be 200, but received " + response.status);
    });
%}
