// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AltTubesColumns holds the columns for the "alt_tubes" table.
	AltTubesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// AltTubesTable holds the schema information for the "alt_tubes" table.
	AltTubesTable = &schema.Table{
		Name:       "alt_tubes",
		Columns:    AltTubesColumns,
		PrimaryKey: []*schema.Column{AltTubesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AltTubesTable,
	}
)

func init() {
}
