// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AltTube-Go/ent/alttube"
	"AltTube-Go/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AltTubeUpdate is the builder for updating AltTube entities.
type AltTubeUpdate struct {
	config
	hooks    []Hook
	mutation *AltTubeMutation
}

// Where appends a list predicates to the AltTubeUpdate builder.
func (atu *AltTubeUpdate) Where(ps ...predicate.AltTube) *AltTubeUpdate {
	atu.mutation.Where(ps...)
	return atu
}

// Mutation returns the AltTubeMutation object of the builder.
func (atu *AltTubeUpdate) Mutation() *AltTubeMutation {
	return atu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (atu *AltTubeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, atu.sqlSave, atu.mutation, atu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atu *AltTubeUpdate) SaveX(ctx context.Context) int {
	affected, err := atu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (atu *AltTubeUpdate) Exec(ctx context.Context) error {
	_, err := atu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atu *AltTubeUpdate) ExecX(ctx context.Context) {
	if err := atu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (atu *AltTubeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(alttube.Table, alttube.Columns, sqlgraph.NewFieldSpec(alttube.FieldID, field.TypeInt))
	if ps := atu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, atu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alttube.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	atu.mutation.done = true
	return n, nil
}

// AltTubeUpdateOne is the builder for updating a single AltTube entity.
type AltTubeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AltTubeMutation
}

// Mutation returns the AltTubeMutation object of the builder.
func (atuo *AltTubeUpdateOne) Mutation() *AltTubeMutation {
	return atuo.mutation
}

// Where appends a list predicates to the AltTubeUpdate builder.
func (atuo *AltTubeUpdateOne) Where(ps ...predicate.AltTube) *AltTubeUpdateOne {
	atuo.mutation.Where(ps...)
	return atuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (atuo *AltTubeUpdateOne) Select(field string, fields ...string) *AltTubeUpdateOne {
	atuo.fields = append([]string{field}, fields...)
	return atuo
}

// Save executes the query and returns the updated AltTube entity.
func (atuo *AltTubeUpdateOne) Save(ctx context.Context) (*AltTube, error) {
	return withHooks(ctx, atuo.sqlSave, atuo.mutation, atuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atuo *AltTubeUpdateOne) SaveX(ctx context.Context) *AltTube {
	node, err := atuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (atuo *AltTubeUpdateOne) Exec(ctx context.Context) error {
	_, err := atuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atuo *AltTubeUpdateOne) ExecX(ctx context.Context) {
	if err := atuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (atuo *AltTubeUpdateOne) sqlSave(ctx context.Context) (_node *AltTube, err error) {
	_spec := sqlgraph.NewUpdateSpec(alttube.Table, alttube.Columns, sqlgraph.NewFieldSpec(alttube.FieldID, field.TypeInt))
	id, ok := atuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AltTube.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := atuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alttube.FieldID)
		for _, f := range fields {
			if !alttube.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alttube.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := atuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &AltTube{config: atuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, atuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alttube.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	atuo.mutation.done = true
	return _node, nil
}
