// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AltTube-Go/ent/likevideo"
	"AltTube-Go/ent/predicate"
	"AltTube-Go/ent/user"
	"AltTube-Go/ent/video"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikeVideoQuery is the builder for querying LikeVideo entities.
type LikeVideoQuery struct {
	config
	ctx        *QueryContext
	order      []likevideo.OrderOption
	inters     []Interceptor
	predicates []predicate.LikeVideo
	withUser   *UserQuery
	withVideo  *VideoQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LikeVideoQuery builder.
func (lvq *LikeVideoQuery) Where(ps ...predicate.LikeVideo) *LikeVideoQuery {
	lvq.predicates = append(lvq.predicates, ps...)
	return lvq
}

// Limit the number of records to be returned by this query.
func (lvq *LikeVideoQuery) Limit(limit int) *LikeVideoQuery {
	lvq.ctx.Limit = &limit
	return lvq
}

// Offset to start from.
func (lvq *LikeVideoQuery) Offset(offset int) *LikeVideoQuery {
	lvq.ctx.Offset = &offset
	return lvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lvq *LikeVideoQuery) Unique(unique bool) *LikeVideoQuery {
	lvq.ctx.Unique = &unique
	return lvq
}

// Order specifies how the records should be ordered.
func (lvq *LikeVideoQuery) Order(o ...likevideo.OrderOption) *LikeVideoQuery {
	lvq.order = append(lvq.order, o...)
	return lvq
}

// QueryUser chains the current query on the "user" edge.
func (lvq *LikeVideoQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: lvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(likevideo.Table, likevideo.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, likevideo.UserTable, likevideo.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(lvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVideo chains the current query on the "video" edge.
func (lvq *LikeVideoQuery) QueryVideo() *VideoQuery {
	query := (&VideoClient{config: lvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(likevideo.Table, likevideo.FieldID, selector),
			sqlgraph.To(video.Table, video.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, likevideo.VideoTable, likevideo.VideoColumn),
		)
		fromU = sqlgraph.SetNeighbors(lvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LikeVideo entity from the query.
// Returns a *NotFoundError when no LikeVideo was found.
func (lvq *LikeVideoQuery) First(ctx context.Context) (*LikeVideo, error) {
	nodes, err := lvq.Limit(1).All(setContextOp(ctx, lvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{likevideo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lvq *LikeVideoQuery) FirstX(ctx context.Context) *LikeVideo {
	node, err := lvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LikeVideo ID from the query.
// Returns a *NotFoundError when no LikeVideo ID was found.
func (lvq *LikeVideoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lvq.Limit(1).IDs(setContextOp(ctx, lvq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{likevideo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lvq *LikeVideoQuery) FirstIDX(ctx context.Context) int {
	id, err := lvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LikeVideo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LikeVideo entity is found.
// Returns a *NotFoundError when no LikeVideo entities are found.
func (lvq *LikeVideoQuery) Only(ctx context.Context) (*LikeVideo, error) {
	nodes, err := lvq.Limit(2).All(setContextOp(ctx, lvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{likevideo.Label}
	default:
		return nil, &NotSingularError{likevideo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lvq *LikeVideoQuery) OnlyX(ctx context.Context) *LikeVideo {
	node, err := lvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LikeVideo ID in the query.
// Returns a *NotSingularError when more than one LikeVideo ID is found.
// Returns a *NotFoundError when no entities are found.
func (lvq *LikeVideoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lvq.Limit(2).IDs(setContextOp(ctx, lvq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{likevideo.Label}
	default:
		err = &NotSingularError{likevideo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lvq *LikeVideoQuery) OnlyIDX(ctx context.Context) int {
	id, err := lvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LikeVideos.
func (lvq *LikeVideoQuery) All(ctx context.Context) ([]*LikeVideo, error) {
	ctx = setContextOp(ctx, lvq.ctx, ent.OpQueryAll)
	if err := lvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LikeVideo, *LikeVideoQuery]()
	return withInterceptors[[]*LikeVideo](ctx, lvq, qr, lvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lvq *LikeVideoQuery) AllX(ctx context.Context) []*LikeVideo {
	nodes, err := lvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LikeVideo IDs.
func (lvq *LikeVideoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lvq.ctx.Unique == nil && lvq.path != nil {
		lvq.Unique(true)
	}
	ctx = setContextOp(ctx, lvq.ctx, ent.OpQueryIDs)
	if err = lvq.Select(likevideo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lvq *LikeVideoQuery) IDsX(ctx context.Context) []int {
	ids, err := lvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lvq *LikeVideoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lvq.ctx, ent.OpQueryCount)
	if err := lvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lvq, querierCount[*LikeVideoQuery](), lvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lvq *LikeVideoQuery) CountX(ctx context.Context) int {
	count, err := lvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lvq *LikeVideoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lvq.ctx, ent.OpQueryExist)
	switch _, err := lvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lvq *LikeVideoQuery) ExistX(ctx context.Context) bool {
	exist, err := lvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LikeVideoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lvq *LikeVideoQuery) Clone() *LikeVideoQuery {
	if lvq == nil {
		return nil
	}
	return &LikeVideoQuery{
		config:     lvq.config,
		ctx:        lvq.ctx.Clone(),
		order:      append([]likevideo.OrderOption{}, lvq.order...),
		inters:     append([]Interceptor{}, lvq.inters...),
		predicates: append([]predicate.LikeVideo{}, lvq.predicates...),
		withUser:   lvq.withUser.Clone(),
		withVideo:  lvq.withVideo.Clone(),
		// clone intermediate query.
		sql:  lvq.sql.Clone(),
		path: lvq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (lvq *LikeVideoQuery) WithUser(opts ...func(*UserQuery)) *LikeVideoQuery {
	query := (&UserClient{config: lvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lvq.withUser = query
	return lvq
}

// WithVideo tells the query-builder to eager-load the nodes that are connected to
// the "video" edge. The optional arguments are used to configure the query builder of the edge.
func (lvq *LikeVideoQuery) WithVideo(opts ...func(*VideoQuery)) *LikeVideoQuery {
	query := (&VideoClient{config: lvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lvq.withVideo = query
	return lvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LikeVideo.Query().
//		GroupBy(likevideo.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lvq *LikeVideoQuery) GroupBy(field string, fields ...string) *LikeVideoGroupBy {
	lvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LikeVideoGroupBy{build: lvq}
	grbuild.flds = &lvq.ctx.Fields
	grbuild.label = likevideo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.LikeVideo.Query().
//		Select(likevideo.FieldCreatedAt).
//		Scan(ctx, &v)
func (lvq *LikeVideoQuery) Select(fields ...string) *LikeVideoSelect {
	lvq.ctx.Fields = append(lvq.ctx.Fields, fields...)
	sbuild := &LikeVideoSelect{LikeVideoQuery: lvq}
	sbuild.label = likevideo.Label
	sbuild.flds, sbuild.scan = &lvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LikeVideoSelect configured with the given aggregations.
func (lvq *LikeVideoQuery) Aggregate(fns ...AggregateFunc) *LikeVideoSelect {
	return lvq.Select().Aggregate(fns...)
}

func (lvq *LikeVideoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lvq); err != nil {
				return err
			}
		}
	}
	for _, f := range lvq.ctx.Fields {
		if !likevideo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lvq.path != nil {
		prev, err := lvq.path(ctx)
		if err != nil {
			return err
		}
		lvq.sql = prev
	}
	return nil
}

func (lvq *LikeVideoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LikeVideo, error) {
	var (
		nodes       = []*LikeVideo{}
		_spec       = lvq.querySpec()
		loadedTypes = [2]bool{
			lvq.withUser != nil,
			lvq.withVideo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LikeVideo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LikeVideo{config: lvq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lvq.withUser; query != nil {
		if err := lvq.loadUser(ctx, query, nodes, nil,
			func(n *LikeVideo, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := lvq.withVideo; query != nil {
		if err := lvq.loadVideo(ctx, query, nodes, nil,
			func(n *LikeVideo, e *Video) { n.Edges.Video = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lvq *LikeVideoQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*LikeVideo, init func(*LikeVideo), assign func(*LikeVideo, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*LikeVideo)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (lvq *LikeVideoQuery) loadVideo(ctx context.Context, query *VideoQuery, nodes []*LikeVideo, init func(*LikeVideo), assign func(*LikeVideo, *Video)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*LikeVideo)
	for i := range nodes {
		fk := nodes[i].VideoID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(video.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "video_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (lvq *LikeVideoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lvq.querySpec()
	_spec.Node.Columns = lvq.ctx.Fields
	if len(lvq.ctx.Fields) > 0 {
		_spec.Unique = lvq.ctx.Unique != nil && *lvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lvq.driver, _spec)
}

func (lvq *LikeVideoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(likevideo.Table, likevideo.Columns, sqlgraph.NewFieldSpec(likevideo.FieldID, field.TypeInt))
	_spec.From = lvq.sql
	if unique := lvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lvq.path != nil {
		_spec.Unique = true
	}
	if fields := lvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, likevideo.FieldID)
		for i := range fields {
			if fields[i] != likevideo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if lvq.withUser != nil {
			_spec.Node.AddColumnOnce(likevideo.FieldUserID)
		}
		if lvq.withVideo != nil {
			_spec.Node.AddColumnOnce(likevideo.FieldVideoID)
		}
	}
	if ps := lvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lvq *LikeVideoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lvq.driver.Dialect())
	t1 := builder.Table(likevideo.Table)
	columns := lvq.ctx.Fields
	if len(columns) == 0 {
		columns = likevideo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lvq.sql != nil {
		selector = lvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lvq.ctx.Unique != nil && *lvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lvq.predicates {
		p(selector)
	}
	for _, p := range lvq.order {
		p(selector)
	}
	if offset := lvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LikeVideoGroupBy is the group-by builder for LikeVideo entities.
type LikeVideoGroupBy struct {
	selector
	build *LikeVideoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lvgb *LikeVideoGroupBy) Aggregate(fns ...AggregateFunc) *LikeVideoGroupBy {
	lvgb.fns = append(lvgb.fns, fns...)
	return lvgb
}

// Scan applies the selector query and scans the result into the given value.
func (lvgb *LikeVideoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lvgb.build.ctx, ent.OpQueryGroupBy)
	if err := lvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikeVideoQuery, *LikeVideoGroupBy](ctx, lvgb.build, lvgb, lvgb.build.inters, v)
}

func (lvgb *LikeVideoGroupBy) sqlScan(ctx context.Context, root *LikeVideoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lvgb.fns))
	for _, fn := range lvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lvgb.flds)+len(lvgb.fns))
		for _, f := range *lvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LikeVideoSelect is the builder for selecting fields of LikeVideo entities.
type LikeVideoSelect struct {
	*LikeVideoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lvs *LikeVideoSelect) Aggregate(fns ...AggregateFunc) *LikeVideoSelect {
	lvs.fns = append(lvs.fns, fns...)
	return lvs
}

// Scan applies the selector query and scans the result into the given value.
func (lvs *LikeVideoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lvs.ctx, ent.OpQuerySelect)
	if err := lvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikeVideoQuery, *LikeVideoSelect](ctx, lvs.LikeVideoQuery, lvs, lvs.inters, v)
}

func (lvs *LikeVideoSelect) sqlScan(ctx context.Context, root *LikeVideoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lvs.fns))
	for _, fn := range lvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
