// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AltTube-Go/ent/likevideo"
	"AltTube-Go/ent/user"
	"AltTube-Go/ent/video"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LikeVideo is the model entity for the LikeVideo schema.
type LikeVideo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// VideoID holds the value of the "video_id" field.
	VideoID string `json:"video_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LikeVideoQuery when eager-loading is set.
	Edges        LikeVideoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LikeVideoEdges holds the relations/edges for other nodes in the graph.
type LikeVideoEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Video holds the value of the video edge.
	Video *Video `json:"video,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LikeVideoEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// VideoOrErr returns the Video value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LikeVideoEdges) VideoOrErr() (*Video, error) {
	if e.Video != nil {
		return e.Video, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: video.Label}
	}
	return nil, &NotLoadedError{edge: "video"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LikeVideo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case likevideo.FieldID:
			values[i] = new(sql.NullInt64)
		case likevideo.FieldUserID, likevideo.FieldVideoID:
			values[i] = new(sql.NullString)
		case likevideo.FieldCreatedAt, likevideo.FieldUpdatedAt, likevideo.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LikeVideo fields.
func (lv *LikeVideo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case likevideo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lv.ID = int(value.Int64)
		case likevideo.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				lv.CreatedAt = value.Time
			}
		case likevideo.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				lv.UpdatedAt = value.Time
			}
		case likevideo.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				lv.DeletedAt = new(time.Time)
				*lv.DeletedAt = value.Time
			}
		case likevideo.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				lv.UserID = value.String
			}
		case likevideo.FieldVideoID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_id", values[i])
			} else if value.Valid {
				lv.VideoID = value.String
			}
		default:
			lv.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LikeVideo.
// This includes values selected through modifiers, order, etc.
func (lv *LikeVideo) Value(name string) (ent.Value, error) {
	return lv.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the LikeVideo entity.
func (lv *LikeVideo) QueryUser() *UserQuery {
	return NewLikeVideoClient(lv.config).QueryUser(lv)
}

// QueryVideo queries the "video" edge of the LikeVideo entity.
func (lv *LikeVideo) QueryVideo() *VideoQuery {
	return NewLikeVideoClient(lv.config).QueryVideo(lv)
}

// Update returns a builder for updating this LikeVideo.
// Note that you need to call LikeVideo.Unwrap() before calling this method if this LikeVideo
// was returned from a transaction, and the transaction was committed or rolled back.
func (lv *LikeVideo) Update() *LikeVideoUpdateOne {
	return NewLikeVideoClient(lv.config).UpdateOne(lv)
}

// Unwrap unwraps the LikeVideo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lv *LikeVideo) Unwrap() *LikeVideo {
	_tx, ok := lv.config.driver.(*txDriver)
	if !ok {
		panic("ent: LikeVideo is not a transactional entity")
	}
	lv.config.driver = _tx.drv
	return lv
}

// String implements the fmt.Stringer.
func (lv *LikeVideo) String() string {
	var builder strings.Builder
	builder.WriteString("LikeVideo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lv.ID))
	builder.WriteString("created_at=")
	builder.WriteString(lv.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(lv.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := lv.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(lv.UserID)
	builder.WriteString(", ")
	builder.WriteString("video_id=")
	builder.WriteString(lv.VideoID)
	builder.WriteByte(')')
	return builder.String()
}

// LikeVideos is a parsable slice of LikeVideo.
type LikeVideos []*LikeVideo
