// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AltTube-Go/ent/schema"
	"AltTube-Go/ent/user"
	"AltTube-Go/ent/video"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	videoFields := schema.Video{}.Fields()
	_ = videoFields
	// videoDescTitle is the schema descriptor for title field.
	videoDescTitle := videoFields[1].Descriptor()
	// video.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	video.TitleValidator = videoDescTitle.Validators[0].(func(string) error)
	// videoDescDescription is the schema descriptor for description field.
	videoDescDescription := videoFields[2].Descriptor()
	// video.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	video.DescriptionValidator = videoDescDescription.Validators[0].(func(string) error)
	// videoDescUploader is the schema descriptor for uploader field.
	videoDescUploader := videoFields[4].Descriptor()
	// video.UploaderValidator is a validator for the "uploader" field. It is called by the builders before save.
	video.UploaderValidator = videoDescUploader.Validators[0].(func(string) error)
	// videoDescUploaderURL is the schema descriptor for uploader_url field.
	videoDescUploaderURL := videoFields[5].Descriptor()
	// video.UploaderURLValidator is a validator for the "uploader_url" field. It is called by the builders before save.
	video.UploaderURLValidator = videoDescUploaderURL.Validators[0].(func(string) error)
	// videoDescThumbnailURL is the schema descriptor for thumbnail_url field.
	videoDescThumbnailURL := videoFields[9].Descriptor()
	// video.ThumbnailURLValidator is a validator for the "thumbnail_url" field. It is called by the builders before save.
	video.ThumbnailURLValidator = videoDescThumbnailURL.Validators[0].(func(string) error)
}
