// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessToken is the predicate function for accesstoken builders.
type AccessToken func(*sql.Selector)

// LikeVideo is the predicate function for likevideo builders.
type LikeVideo func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Video is the predicate function for video builders.
type Video func(*sql.Selector)
